### ISSUE TITLE
Nil value bug

### ISSUE THREAD

**Issue by ianejames** [igrigorik/em-http-request#259]
After upgrading to 1.1.2 (from 1.1.1), I'm getting the following error from the 'eventmachine' library:

<pre><samp>FATAL 13:00:03.009 ~ can't convert nil into String
</samp></pre>
Here's the backtrace:

<pre><samp>RVM_DIR/gems/eventmachine-1.0.3/lib/eventmachine.rb:776:in `connect_server'
RVM_DIR/gems/eventmachine-1.0.3/lib/eventmachine.rb:776:in `reconnect'
RVM_DIR/gems/eventmachine-1.0.3/lib/em/connection.rb:628:in `reconnect'
RVM_DIR/gems/em-http-request-1.1.2/lib/em-http/http_connection.rb:187:in `unbind'
RVM_DIR/gems/em-http-request-1.1.2/lib/em-http/http_connection.rb:31:in `unbind'
RVM_DIR/gems/eventmachine-1.0.3/lib/eventmachine.rb:1438:in `event_callback'
RVM_DIR/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run_machine'
RVM_DIR/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run'
RVM_DIR/gems/thin-1.6.1/lib/thin/backends/base.rb:73:in `start'
RVM_DIR/gems/thin-1.6.1/lib/thin/server.rb:162:in `start'
RVM_DIR/gems/rack-1.5.2/lib/rack/handler/thin.rb:16:in `run'
RVM_DIR/gems/sproutcore-1.10.2/lib/sproutcore/rack/service.rb:93:in `start'
RVM_DIR/gems/sproutcore-1.10.2/lib/sproutcore/tools/server.rb:71:in `server'
RVM_DIR/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
RVM_DIR/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
RVM_DIR/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
RVM_DIR/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
RVM_DIR/gems/sproutcore-1.10.2/lib/sproutcore/tools.rb:445:in `start'
RVM_DIR/gems/sproutcore-1.10.2/lib/sproutcore/tools.rb:30:in `invoke'
RVM_DIR/gems/sproutcore-1.10.2/bin/sc-server:11:in `<top (required)>'
RVM_DIR/bin/sc-server:19:in `load'
RVM_DIR/bin/sc-server:19:in `<main>'
RVM_DIR/bin/ruby_noexec_wrapper:14:in `eval'
RVM_DIR/bin/ruby_noexec_wrapper:14:in `<main>'
</samp></pre>

The fix is to revert commit 043eb0 -- specifically the change to the file "lib/em-http/http_connection.rb".

**Comment by igrigorik** [comment]
Pruning issues, let's continue discussing on the pull.
