### ISSUE TITLE
Uses String#getbyte which is not available in ruby 1.8

### ISSUE THREAD

**Issue by flagman** [igrigorik/em-http-request#272]
/opt/ruby-enterprise-1.8.7-2012.02/lib/ruby/gems/1.8/gems/em-http-request-1.1.2/lib/em-http/decoders.rb:139:in `extract_stream': undefined method `getbyte' for "\037\213\b\000\000\000\000\000\004\000":String (NoMethodError)

**Comment by igrigorik** [comment]
Apologies about the delay. Ruby 1.8.x is deprecated and no longer maintained.. I'll add a gemspec entry to require 1.9+.
