### ISSUE TITLE
https:///host.com/ causes Seg Fault on solaris (three forward slashes instead of two)

### ISSUE THREAD

**Issue by sodabrew** [igrigorik/em-http-request#280]
@wkonkel opened eventmachine/eventmachine#376 on Oct 24, 2012. I don't know if this is an open issue, I haven't tried the repro below as yet. I'm closing out the issue on the eventmachine side since EM::MultiRequest lives here.

Due to a bug in our code, three slashes were appearing in a URL instead of the normal two. What was unexpected was a segfault.

```ruby
EM.run do
  multi = EM::MultiRequest.new
  url = 'https:///ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js'
  multi.add(url, EM::HttpRequest.new(url).get)
  multi.callback {EM.stop}
end
```

Ruby: ruby 1.9.2p290 (2011-07-09 revision 32553) [x86_64-solaris2.11]

Full trace: https://gist.github.com/5f011dc347fd95e24ef2

**Comment by igrigorik** [comment]
But the segfault is in EM.. so I think the bug belongs there. =/

**Comment by sodabrew** [comment]
Oh, I wonder if there is a small repro case that doesn't need to loop in MultiRequest to trigger?

**Comment by igrigorik** [comment]
There is nothing special in MultiRequest (https://github.com/igrigorik/em-http-request/blob/master/lib/em-http/multi.rb), so yeah, I'd expect this to be easily reproducible outside of it (but I don't have a Solaris system to test this theory on :)).

**Comment by sodabrew** [comment]
I've got a Solaris VM.... Oh yep that smaller test case crashes on Solaris 11.2. Ok, closing here, reopening in eventmachine with the smaller repro case.
