### ISSUE TITLE
HTTPS proxying generates a stray colon in CONNECT statement

### ISSUE THREAD

**Issue by jan** [igrigorik/em-http-request#292]
When running a GET request with a proxy to a HTTPS URI that either does not specify a port or specifies the standard port 443, the CONNECT statement looks like this:

    CONNECT www.google.de: HTTP/1.0\r\n

Note the colon after www.google.de. When I (falsely) specify port 80 in the URI, this line looks like this:

    CONNECT www.google.de:80 HTTP/1.0\r\n

I think that it is wrong to place a colon here, although I must confess, that I didn't find the relevant RFC.
What I can say is that 
- Firefox generates with a port: `CONNECT www.google.de:443 HTTP/1.1`
- the gem `http_parser.rb` cannot parse the above line. 

I guess, some proxy servers will be robust to this and others won't.

**Comment by igrigorik** [comment]
That's definitely an error on this end. Looks like we set the port to nil which then comes out as empty string.

**Comment by jan** [comment]
Apparently this was already fixed in February, but no new version of the gem was released since.
https://github.com/igrigorik/em-http-request/commit/74efe8e3447ee16a22d00fa9cf1d0224dae09db7
When do you plan to release a new version?

**Comment by igrigorik** [comment]
Pushed out 1.1.3 - https://github.com/igrigorik/em-http-request/commit/a4476c89a0f2e46454470cfff0edbd26ed2a688d.

**Comment by jan** [comment]
Great! Thank you, @igrigorik!
