### ISSUE TITLE
Handling multiple responses to one HTTP request

### ISSUE THREAD

**Issue by d0minos** [igrigorik/em-http-request#293]
Hi,

I have been using this gem for several years without any issues. However, it appears I have now stumbled upon a corner case, which the library is not able to handle.

Namely, if one HTTP request receives duplicate responses (instead of one, which is normal), the following crash will occur:
```
/data/applications/my-app/shared/bundle/ruby/1.8/gems/em-http-request-1.1.2/lib/em-http/http_connection.rb:117:in `post_init': undefined method `parse_response_header' for nil:NilClass (NoMethodError)
        from /data/applications/my-app/shared/bundle/ruby/1.8/gems/em-http-request-1.1.2/lib/em-http/http_connection.rb:144:in `call'
        from /data/applications/my-app/shared/bundle/ruby/1.8/gems/em-http-request-1.1.2/lib/em-http/http_connection.rb:144:in `<<'
        from /data/applications/my-app/shared/bundle/ruby/1.8/gems/em-http-request-1.1.2/lib/em-http/http_connection.rb:144:in `receive_data'
        from /data/applications/my-app/shared/bundle/ruby/1.8/gems/em-http-request-1.1.2/lib/em-http/http_connection.rb:23:in `receive_data'
        from /data/applications/my-app/shared/bundle/ruby/1.8/gems/eventmachine-1.0.8/lib/eventmachine.rb:193:in `run_machine'
        from /data/applications/my-app/shared/bundle/ruby/1.8/gems/eventmachine-1.0.8/lib/eventmachine.rb:193:in `run'
        from /data/applications/my-app/shared/bundle/ruby/1.8/gems/thin-1.5.0/lib/thin/backends/base.rb:63:in `start'
        from /data/applications/my-app/shared/bundle/ruby/1.8/gems/thin-1.5.0/lib/thin/server.rb:159:in `start'
        from /data/applications/my-app/shared/bundle/ruby/1.8/gems/thin-1.5.0/lib/thin/controllers/controller.rb:86:in `start'
        from /data/applications/my-app/shared/bundle/ruby/1.8/gems/thin-1.5.0/lib/thin/runner.rb:187:in `send'
        from /data/applications/my-app/shared/bundle/ruby/1.8/gems/thin-1.5.0/lib/thin/runner.rb:187:in `run_command'
        from /data/applications/my-app/shared/bundle/ruby/1.8/gems/thin-1.5.0/lib/thin/runner.rb:152:in `run!'
        from /data/applications/my-app/shared/bundle/ruby/1.8/gems/thin-1.5.0/bin/thin:6
        from /home/user/.rbenv/versions/1.8.7-p374/bin/thin:19:in `load'
        from /home/user/.rbenv/versions/1.8.7-p374/bin/thin:19
```

To illustrate this further, I will add the ngrep logs, which I took when this issue happened:
```
T 2015/10/13 11:14:53.373324 xxx.xxx.xxx.xxx:xxxxx -> yyy.yyy.yyy.yyy:yyyy [AP]
GET /some/path HTTP/1.1.
User-Agent: EventMachine HttpClient.
Host: yyy.yyy.yyy.yyy.
Connection: close.
.


T 2015/10/13 11:14:53.648916 yyy.yyy.yyy.yyy:yyyy -> xxx.xxx.xxx.xxx:xxxxx [AP]
HTTP/1.1 403 Forbidden.
Content-Type: text/plain.
Content-Length: 13.
.
403 Forbidden

T 2015/10/13 11:14:53.648945 yyy.yyy.yyy.yyy:yyyy -> xxx.xxx.xxx.xxx:xxxxx [AP]
HTTP/1.1 403 Forbidden.
Content-Type: text/plain.
Content-Length: 13.
.
403 Forbidden
```

As you can see, there was one request made but the server responded with 2 identical responses, which arrived at very short intervals. The first response was handled correctly but upon receiving the second one the variable 'client' in http_connection.rb was not initialized, resulting in failure.

The code used to get this exception is rather standard:
```
http = EventMachine::HttpRequest.new(url).get
http.callback do
  # callback logic
end
http.errback do
  # errback  logic
end
```

This is probably a result of misconfiguration on someone's server (returning 2 responses) but still, maybe there is a better way to handle this situation instead of crashing? I tested some other HTTP libraries and they seemed to work fine with this type of response, simply discarding the second part.

For me this is a rather serious issue since I'm using this library within a thin web server. Any exceptions thrown in EM event loop result in thin crashing as well, so it has potential to take my site down.

Are there any ideas how this could be solved?

**Comment by igrigorik** [comment]
What server is this? This is definitely _not_ valid HTTP behavior.

**Comment by d0minos** [comment]
I agree this is not valid HTTP behaviour. But I was never saying it was.

The main issue here is that by sending such response to the application, it's possible to cause a crash within the event loop. As a developer I have no control over what's happening inside the loop (all logic comes from the gems(s)) and therefore cannot handle the exceptions that happen in there. As I mentioned in the opening post, uncaught exceptions in event loop can cause issues (e.g. thin webserver not able to recover from it).

So, it's mainly a security issue. A malicious user might send such invalid response on purpose to cause crash within the application and potentially take down the whole site. Or someone could do it inadvertently with the same results.

As for the server, it has been fixed and no longer returns such duplicate response.

**Comment by igrigorik** [comment]
Yep, that's fair. That was more my own curiosity because if that's a mildly popular server.. then that's a problem that needs to be addressed in there as well. 

As far as fixing this, we'd need to check that `client` is available and unbind/close the connection if not: https://github.com/igrigorik/em-http-request/blob/master/lib/em-http/http_connection.rb#L117.

**Comment by d0minos** [comment]
Yes, I assume this approach could work for a fix.
Not sure if it's relevant in case we close/unbind the connection but we also need to make sure that `on_body` and `on_message_complete` blocks don't get called (since they also need an existing `client`). If I simply skipped the `on_headers_complete` when `client` was missing, the flow moved forward to the aforementioned blocks and also could have caused issues there.

**Comment by igrigorik** [comment]
I think this should do the trick: https://github.com/igrigorik/em-http-request/commit/3a9b96c2f31f29c112a11b934fee7d40cafd4dcc. Can you try with your server and confirm?

**Comment by d0minos** [comment]
Sorry for the late response. As I mentioned, the original server with invalid responses has been fixed, so I had create one such server myself to validate the solution.

Anyway, this is a simple broken server I came up with. Based on ngrep logs, it seems to return similar responses to the original server.
```
class BrokenServer < EventMachine::Connection
  def receive_data(data)
    puts "Data received from client (length: #{data.length}):\n#{data}"
    body = '403 Forbidden'
    response = "HTTP/1.1 403 Forbidden\r\nContent-Type: text/plain\r\nContent-Length: #{body.bytesize}\r\n\r\n#{body}"
    EM.add_timer(1) do
      send_data(response)
      puts "\n#{response}\n"
    end
    EM.add_timer(2) do
      send_data(response)
      puts "\n#{response}\n"
    end
  end

  def unbind
    puts 'Connection terminated'
  end

  def post_init
    puts 'Incoming connection'
  end
end

EM.run do
  host = '127.0.0.1' # accept connections from
  port = 16169 # port to listen
  EM.start_server host, port, BrokenServer
  puts "Started BrokenServer on #{host}:#{port}."
end
```

I made the tests with the following code snippet:
```
def make_request
  http = EventMachine::HttpRequest.new('http://127.0.0.1:16169').get
  http.callback do
    puts http.response_header.status
    puts http.response
  end
  http.errback { puts 'error' }
end

EM.run { make_request }
```

Based on the results, it seems your fix has worked. When I ran it with gem version 1.1.2, the expected exception was raised. With the latest version of branch master there was no such exception and only the first of the duplicate responses was handled.

So, all seems fine on my side.

**Comment by igrigorik** [comment]
@d0minos thanks for verifying! :+1:  Closing.

**Comment by d0minos** [comment]
Thanks.
Appreciate the fast resolution.
