### ISSUE TITLE
Drop dependency on http_parser.rb

### ISSUE THREAD

**Issue by greg-hellings** [igrigorik/em-http-request#294]
This library is still listed as pre-release (version 0.6.0)
It has seen no updates to github since 2014 and to its released gem since 2013
This dependency brings in a transitive dependency on the YAJL-ruby gem, which is not able to be bundled into system package managers because it includes a patched version of YAJL, cannot be unbundled from it, and has itself been inactive for a few years.

**Comment by igrigorik** [comment]
Practically speaking, I don't think this is feasible. We'd have to reimplement the entire HTTP/1.x parser. 

The fact that there have been no updates or releases is, by itself, not a bad sign.. It's a feature complete library that's in use by any existing applications.

**Comment by greg-hellings** [comment]
Does it give you notable benefits over the built-in WEBrick libraries?

My main problem is with the transitive dependency on yajl-ruby, which is a non-starter for system packaging and is effectively abandonware at this point.

**Comment by igrigorik** [comment]
Webrick libraries do not get us very far. The yajl-ruby dependency is dev-only..

**Comment by greg-hellings** [comment]
It's necessary to run the test suite, which it would be really nice to be able to run. I'll see how far I can get without it.
