### ISSUE TITLE
unable to resolve server address: Success

### ISSUE THREAD

**Issue by dgutov** [igrigorik/em-http-request#299]
This is the error we're getting when the host can't be resolved. Both in production and locally, if I run this example script in IRB:

```rb
    EM.run {
      http = EM::HttpRequest.new('http://xxxxxxxxxx.co').get
      http.callback { p 'success'; EM.stop }
      http.errback { puts http.error; EM.stop }
    }
```

em-http-request 1.1.3
eventmachine 1.0.9.1
ruby 1.9.3p547

I'm also getting the same error when running the example script inside `bundle exec irb` within a local checkout of the current master branch. However, if I try to convert this example to a spec inside `dns_spec.rb`, it outputs `unable to resolve server address: Inappropriate ioctl for device` instead.

Expected behavior: have the hostname which failed to resolve there instead of "Success" or the other error.

**Comment by igrigorik** [comment]
We rely on EM to perform the resolution: https://github.com/igrigorik/em-http-request/blob/master/lib/em-http/http_connection.rb#L55-L87

Can you try your example directly with EM.bind_connect?

**Comment by dgutov** [comment]
It's the same:

```
irb(main):005:0> EM.run { EM.bind_connect(nil, nil, 'xxxxxx.co', 80); EM.stop }
EventMachine::ConnectionError: unable to resolve server address: Success
	from /home/gutov/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:677:in `connect_server'
	from /home/gutov/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:677:in `bind_connect'
	from (irb):5:in `block in irb_binding'
	from /home/gutov/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `call'
	from /home/gutov/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run_machine'
	from /home/gutov/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run'
	from (irb):5
	from /home/gutov/.rbenv/versions/1.9.3-p547/bin/irb:12:in `<main>'
irb(main):006:0> EventMachine::VERSION
=> "1.2.0.1"
```

Should I move this issue there?
