### ISSUE TITLE
Literal IPv6 address support

### ISSUE THREAD

**Issue by foca** [igrigorik/em-http-request#304]
Right now, creating a request with a literal IPv6 address will fail, because `URI#host` does not unwrap the brackets from the URI.

I tried to [come up with a patch](https://github.com/igrigorik/em-http-request/compare/master...foca:ipv6_support). This works when tested in IRB but I'm not sure where to start with the tests as I'm not very familiar with EventMachine. Also not sure if I'm covering all the edge cases (I just searched for every call to URI#host and changed that for #hostname.)

https://github.com/lostisland/faraday/pull/621 has some more context on this.

**Comment by igrigorik** [comment]
@foca a good start is to apply the patch and make sure that existing tests still pass. 

bundle install && bundle exec rake spec

From there, take a look at the [client_spec](https://github.com/igrigorik/em-http-request/blob/master/spec/client_spec.rb) and add a case or two for ipv6 case you're after.

**Comment by igrigorik** [comment]
@foca did you have any luck with the tests, etc? Would love to land this.

**Comment by igrigorik** [comment]
Resolved, closing.
