### ISSUE TITLE
how can i send one file with HttpRequest.post

### ISSUE THREAD

**Issue by wllzhazha** [igrigorik/em-http-request#305]
hi

The restful api need a file params, so my code as below:
image1 = File.open("images/face_01.jpg")
    http = EventMachine::HttpRequest.new('http://127.0.0.1:8080/synAdd').post :body=>{"dbName"=>"test", "imageDatas"=>image1}

and it fails, so how can i send a file with the post method? Thanks a lot!

**Comment by igrigorik** [comment]
You have to encode the binary data into a format that your server can understand.. E.g. Read the file and base64 encode it, or some such. 

```Base64.encode64(File.open("file_path", "rb").read)```

**Comment by wllzhazha** [comment]
Thanks a lot!
But the server just accept the type of param is File, not string, i don't know how to send  the File param by HttpRequest.post. 
And i tried the Restclient as below:

image1 = File.open("/images/face_01.jpg")
payload = {"dbName"=>"test","imageDatas"=>image1}
res = RestClient::Request.execute(method: method,
  url: "#{uri}",
  verify_ssl: false,
  payload: payload)
and i captured the http packet by RestClient is :
[:type, "image/jpeg"][:name, "imageDatas"][:tempfile, #<Tempfile:/tmp/RackMultipart20161208-49938-8wvo5b.jpg>][:head, "Content-Disposition: form-data; name=\"imageDatas\"; filename=\"face_01.jpg\"\r\nContent-Type: image/jpeg\r\n"]' 

so i don't know how to send the File param by HttpRequest, thanks !

**Comment by igrigorik** [comment]
You have to consult your server for the exact format it expects: how the file is encoded, how meta-data is delivered, etc. Unfortunately this is not something we can answer here..
