### ISSUE TITLE
Any way to send multipart/form-data?

### ISSUE THREAD

**Issue by ktimothy** [igrigorik/em-http-request#310]
Is it supported?

**Comment by igrigorik** [comment]
Yep. Take a look at the previous discussions on this (i.e. closed issues). A few relevant resources:

- https://gist.github.com/scsmith/778639 + https://github.com/CloudMailin/multipart_body
  - from https://github.com/igrigorik/em-http-request/issues/159
- https://github.com/igrigorik/em-http-request/wiki/Streaming

**Comment by ktimothy** [comment]
Thank you for the links!
