### ISSUE TITLE
Migrate away from Mongrel.

### ISSUE THREAD

**Issue by michielboekhoff** [igrigorik/em-http-request#319]
The test suite is currently failing because Mongrel support has officially been removed from Rack. Furthermore, Mongrel is unmaintained. We should migrate away from it and to something maintained, e.g. WEBrick. I'd be happy to pick this up.

This relates to #318.

**Comment by michielboekhoff** [comment]
@igrigorik @jackorp - just so you know, it might be a week or so before I get a chance to pick this up. If it's needed urgently, feel free to pick it up.

**Comment by igrigorik** [comment]
Per https://github.com/igrigorik/em-http-request/pull/327, closing.
