### ISSUE TITLE
support to send response to client ?

### ISSUE THREAD

**Issue by ashwintastic** [igrigorik/em-http-request#325]
resp = EM::HttpRequest.new('https://jsonplaceholder.typicode.com/posts/1')
      http = resp.get
      http.callback do |r|
      #send_data ">>>you sent: #{r.response}" not receiving response on postman
    end

I'm calling this code from postman but not getting any response there

**Comment by igrigorik** [comment]
That's not the correct request/response flow. If you want to send data to the endpoint, you must pass the data either as a request body, or as part of the query string. Both of those must be provided before the callback.. the callback is what's fires once you get the response back from the server.

E.g. https://github.com/igrigorik/em-http-request/wiki/Issuing-Requests#posting-data

**Comment by ashwintastic** [comment]
**the callback is what's fires once you get the response back from the server.**
  I want to send response which I get from server to the client

**Comment by igrigorik** [comment]
You already have the response. 

```
      http.callback {
        p http.response_header.status
        p http.response_header
        p http.response
      }
```

**Comment by ashwintastic** [comment]
yes it is only printing the response but I'm not getting anything in the postman also the request/response cycle does not ends
