### ISSUE TITLE
Cancel an HTTP request

### ISSUE THREAD

**Issue by hartator** [igrigorik/em-http-request#326]
Let's say I am using multiples proxies to get the same page via `EventMachine::MultiRequest.new`.

Something like this:

```
EventMachine.run do
  multi = EventMachine::MultiRequest.new

  multi.add :google_1, EventMachine::HttpRequest.new('http://www.google.com/', connection_opts_1).get
  multi.add :google_2, EventMachine::HttpRequest.new('http://www.google.com/', connection_opts_1).get
end
```

Is there a way to cancel the other request when the other one successfully get the result first?

Thanks for awesome work on this gem btw.

**Comment by igrigorik** [comment]
Sadly, not really. See: https://github.com/igrigorik/em-http-request/issues/256

In http/2, you can reset a stream, but in http/1.. not so much.

**Comment by hartator** [comment]
Thanks for the answer!
