### ISSUE TITLE
License information for stallion.rb

### ISSUE THREAD

**Issue by hrieke** [igrigorik/em-http-request#329]
Stallion.rb states in the header:
# #--
# Includes portion originally Copyright (C)2008 Michael Fellinger
# license See file LICENSE for details
# #--

I am unable to find the license information mention, nor where the source originates from.
Kinda important to have this cleared up.
Thanks!

**Comment by igrigorik** [comment]
Oi, good catch, thanks for flagging this.

@manveru having a hard time finding the relevant repo. Do you, by any chance, have a pointer?

**Comment by manveru** [comment]
It's probably from https://github.com/manveru/ehttp/blob/master/spec/stallion.rb - which I never put under a license. I haven't really looked at this for 10 years, but the code is from me originally and I have no issues putting it under MIT license if you'd like that.

I never used ehttp for anything but experimentation, so it's kinda cool to see that it actually had some use for someone :)

**Comment by igrigorik** [comment]
Thanks for the quick response Michael. If I have your approval, I propose we update header to:

```
# #--
# Includes portion originally Copyright (C)2008 Michael Fellinger
# MIT License
# #--
```

Does that look reasonable?

**Comment by manveru** [comment]
Sure, that looks fine

**Comment by hrieke** [comment]
Thanks!
