### ISSUE TITLE
Cannot submit both file stream and body

### ISSUE THREAD

**Issue by hexgnu** [igrigorik/em-http-request#54]
When trying to submit both a body and a file part in a post this wont happen since em-http-request is using either or logic.  

I'm going to create a fork of this to fix it.

**Comment by bogdanRada** [comment]
any chance for this to be supported in the future? I did asked same question here: #159 . Not sure though where should i ask this.

**Comment by igrigorik** [comment]
@bogdanRada no, because this use case doesn't make sense. If you need to augment your payload with additional data then you should read it in, run your logic, and then POST it. You can't invoke sendfile _and_ specify a different payload.

**Comment by bogdanRada** [comment]
Ok. Thank you very much for your prompt response. I was able to use faraday with typhoeus adapter as a workaround.
